# Generated by Django 5.0.1 on 2024-03-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_renew', 'Set renewed book'), ('can_view_bookinstance', 'Can view bookinstance'))},
        ),
    ]
