# Generated by Django 5.0.1 on 2024-03-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, height_field='Submit a cover of the book', null=True, upload_to='images/'),
        ),
    ]
