# Generated by Django 5.0.1 on 2024-03-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, help_text='Submit a cover of the book', null=True, upload_to='images/', verbose_name='Book Cover'),
        ),
    ]
